# Generated by Django 5.1.7 on 2025-06-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("departamento", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="departamento",
            name="departamento_imagem",
            field=models.ImageField(blank=True, upload_to="fotos/departamentos"),
        ),
    ]
