# Generated by Django 5.2 on 2025-04-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_nome', models.CharField(max_length=50, unique=True)),
                ('categoria_imagem', models.ImageField(blank=True, upload_to='fotos/categorias')),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
