# Generated by Django 5.1.7 on 2025-04-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categoria", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="descricao",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
