# Generated by Django 5.2 on 2025-05-23 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categoria", "0002_alter_categoria_descricao"),
        ("departamento", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="departamento",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="departamento.departamento",
            ),
        ),
    ]
