# Generated by Django 5.2 on 2025-07-06 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("produto", "0009_alter_produto_promocao_valor_porcentagem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "sobrenome",
                    models.CharField(max_length=100, verbose_name="Sobrenome"),
                ),
                (
                    "endereco",
                    models.CharField(max_length=255, verbose_name="Logradouro"),
                ),
                (
                    "numero_endereco",
                    models.CharField(max_length=20, verbose_name="Número"),
                ),
                (
                    "complemento_endereco",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Complemento",
                    ),
                ),
                ("estado", models.CharField(max_length=50, verbose_name="Estado")),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
                ("cep", models.CharField(max_length=9, verbose_name="CEP")),
                (
                    "telefone",
                    models.CharField(max_length=20, verbose_name="Telefone celular"),
                ),
                ("cpf", models.CharField(max_length=14, verbose_name="CPF")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Subtotal"
                    ),
                ),
                (
                    "valor_imposto",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor do Imposto"
                    ),
                ),
                (
                    "valor_frete",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Valor do Frete",
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Total"
                    ),
                ),
                (
                    "metodo_pagamento",
                    models.CharField(
                        choices=[("PIX", "Pix"), ("CARD", "Crédito/Débito")],
                        max_length=20,
                        verbose_name="Método de Pagamento",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("PAGO", "Pago"),
                            ("ENVIADO", "Enviado"),
                            ("ENTREGUE", "Entregue"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "ordering": ("-criado_em",),
            },
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preco_item",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço (unidade)"
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(default=1, verbose_name="Quantidade"),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_pedido",
                        to="produto.produto",
                        verbose_name="Produto",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="checkout.pedido",
                        verbose_name="Pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Pedido",
                "verbose_name_plural": "Itens do Pedido",
            },
        ),
    ]
