# Generated by Django 5.2 on 2025-07-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="status",
            field=models.CharField(
                choices=[("PENDENTE", "Pendente"), ("PAGO", "Pago")],
                default="PENDENTE",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
