# Generated by Django 5.2 on 2025-05-08 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categoria", "0002_alter_categoria_descricao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("produto_nome", models.CharField(max_length=50, unique=True)),
                (
                    "produto_imagem",
                    models.ImageField(blank=True, upload_to="fotos/produtos"),
                ),
                ("descricao", models.CharField(blank=True, max_length=1000)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("estoque", models.IntegerField(default=0)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categoria.categoria",
                    ),
                ),
            ],
        ),
    ]
