# Generated by Django 5.2 on 2025-05-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="esta_disponivel",
            field=models.BooleanField(default=True),
        ),
    ]
