# Generated by Django 5.2 on 2025-06-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0004_alter_produto_promocao_valor_porcentagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="imposto",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
