# Generated by Django 5.1.7 on 2025-06-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0005_produto_imposto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="imposto",
            field=models.DecimalField(
                blank=True, decimal_places=0, default=0, max_digits=2
            ),
        ),
    ]
