# Generated by Django 5.2 on 2025-07-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0008_alter_produto_imposto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="promocao_valor_porcentagem",
            field=models.DecimalField(
                blank=True, decimal_places=0, default=0, max_digits=2
            ),
        ),
    ]
