# Generated by Django 5.1.7 on 2025-07-02 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("produto", "0006_alter_produto_imposto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favoritos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fav_id", models.CharField(blank=True, max_length=250)),
                ("data_criado", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FavItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("esta_disponivel", models.BooleanField(default=True)),
                ("quantidade", models.PositiveIntegerField(default=0)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produto.produto",
                    ),
                ),
                (
                    "favoritos",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="favoritos.favoritos",
                    ),
                ),
            ],
        ),
    ]
