# Generated by Django 5.2 on 2025-07-02 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favoritos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritos',
            old_name='car_id',
            new_name='fav_id',
        ),
    ]
